apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}-selector"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}-selector"
        version: "current"
      annotations:
        release-time: {{ now }}
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: "{{ .Values.image.registry }}/{{ .Values.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
        env:
          - name: APPCONFIG_SERVICES_SERVER_PORT
            value: "{{ .Values.servicePort }}"
{{- if .Values.env }}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
{{- end }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretsName }}
