apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
  selector:
    app: "{{ .Values.name }}-selector"
